# docker-compose.yml
version: "3"

networks:
  postgres:
    driver: bridge

volumes:
  pg_data:


services:
  app:
    build: .
    ports:
      - "80:80"
    networks:
      - postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    networks:
      - postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    networks:
      - postgres
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
